services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    environment: 
      - 'CLI_JAVA_OPTS=-Xms2g -Xmx2g'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'xpack.security.enrollment.enabled=false'
    networks:
      - elastic
      - esbeat
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
#    ports:
#      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - kibanadata:/usr/share/kibana/data
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

  wifibeat:
    image: wifibeat
    container_name: wifibeat
    privileged: true
    network_mode: host
    pid: host
    networks:
      - esbeat

# See https://docs.docker.com/compose/networking/

networks:
  elastic:
  esbeat:

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local